todo/models.py
from flask import current_app
from flask_sqlalchemy import SQLAlchemy

from datetime import date

db = SQLAlchemy()


class Entry(db.Model):
    id = db.Column("entry_id", db.Integer, primary_key=True)
    body = db.Column(db.String(128))
    date_created = db.Column(db.Date())
    is_done = db.Column(db.Boolean(False))

    def __init__(self, body):
        self.body = body
        self.date_created = date.today()
        self.is_done = False

todo/__init__.py
import os
from flask import Flask

from . import models


def create_app(config=None):
    app = Flask(__name__)
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///todo.sqlite3"
    app.config["SECRET_KEY"] = "dev"

    from . import models
    
    models.db.init_app(app)

    with app.app_context():
        models.db.create_all()

    from . import views

    app.register_blueprint(views.todo)

    return app

todo/views.py
from flask import (
    redirect,
    request,
    url_for,
    Blueprint,
    render_template
)
from flask_sqlalchemy import model
from sqlalchemy.orm import session

from . import models

todo = Blueprint("todo", __name__)


def get_entry(id):
    return models.Entry.query.filter(models.Entry.id == id).first()


def get_entries():
    return models.db.session.query(models.Entry).order_by(models.Entry.is_done)


@todo.route("/", methods=["GET"])
def index():
    return render_template("todo/index.html", entries=get_entries())


@todo.route("/new", methods=["POST"])
def new():
    entry = models.Entry(request.form["body"])
    models.db.session.add(entry)
    models.db.session.commit()

    return redirect("/")


@todo.route("/delete/<int:id>", methods=["POST"])
def delete(id):
    models.db.session.delete(get_entry(id))
    models.db.session.commit()

    return redirect("/")


@todo.route("/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    entry = get_entry(id)

    if request.method == "POST" and entry is not None:
        entry.body = request.form["body"]
        models.db.session.commit()

        return redirect("/")

    return render_template("todo/edit.html", entry=entry)


@todo.route("/done/<int:id>", methods=["GET", "POST"])
def done(id):
    entry = get_entry(id)

    if request.method == "POST" and entry is not None:
        entry.is_done = not entry.is_done
        models.db.session.commit()

        return redirect("/")

    return render_template("todo/edit.html", entry=entry)

todo/templates/base.html
<!DOCTYPE html>
<title>flask-todo</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<header>
    <h1>flask-todo</h1>
</header>
<section class="content">
    {% block content %}{% endblock %}
</section>

todo/templates/todo/edit.html
{% include 'base.html' %}

{% block content %}
    <div class="entry">
        <form action="{{ url_for('todo.edit', id=entry.id) }}" method="post">
            <input class="button edit-text" type="text" name="body" value="{{ request.form["body"] or entry.body }}" required>
            <input class="button yellow" type="submit" name="save" value="Save">
        </form>
        <br>
        <form action="{{ url_for('todo.delete', id=entry.id) }}" method="post">
            <input class="hide" type="text" name="id" value="{{ entry.id }}" readonly>
            <input class="button red" type="submit" name="remove" value="Delete">
        </form>
    </div>
{% endblock %}

todo/templates/todo/index.html
{% extends 'base.html' %}

{% block content %}
    <form class="controls" action="{{ url_for('todo.new') }}" method="post">
        <input type="text" name="body" required>
        <input class="button green" type="submit" value="Add">
    </form>

    <div class="entries">
        {% for e in entries %}
            {% if e.is_done %}
                <div class="entry inactive">
            {% else %}
                <div class="entry">
            {% endif %}
                <p class="body">{{ e.body }}
                    {% if not e.is_done %}
                    (<a href="{{ url_for('todo.edit', id=e.id) }}">Edit</a>)
                    {% endif %}
                </p>
                <p class="date">{{ e.date_created }}</p>
                <form action="{{ url_for('todo.done', id=e.id) }}" method="post">
                    {% if e.is_done %}
                        <input class="button yellow" type="submit" value="Undo">
                    {% else %}
                        <input class="button green" type="submit" value="Done">
                    {% endif %}
                </form>
            </div>
        {% endfor %}
    </div>
{% endblock %}